### PR TITLE
Add Lazy Command Support

### PR DESCRIPTION
**Pull request by jordisala1991**
This PR address this issue: #185 

I tried to add a test first to show the problem and on the second commit added the fix. Not sure if it is the best way to fix it because I don't know a lot of the internals of PHPStan.

### CODE REVIEW

**Comment by jordisala1991** [comment]
I need a workflow approval to show the failure on Github Actions.

**Comment by VincentLanglet** [comment]
> I need a workflow approval to show the failure on Github Actions.

The approval is needed after every commit, so if you already have a fix to try, you should push it.
As a quick win I can open draft PR with cherry-pick of the commit, since I don't need approval (pretty annoying feature...)

**Comment by VincentLanglet** [comment]
Tests are here https://github.com/phpstan/phpstan-symfony/pull/187 @jordisala1991.

Seems like highest tests are working but not lowest, phpstan and cs.

**Comment by jordisala1991** [comment]
> Tests are here https://github.com/phpstan/phpstan-symfony/pull/187 @jordisala1991.
> 
> 
> 
> Seems like highest tests are working but not lowest, phpstan and cs.

I will try to fix it tomorrow

**Comment by ondrejmirtes** [comment]
LazyCommands are a pretty recent invention so please feel free to run the tests conditionally, thanks.

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
