### PR TITLE
Adds stub file for PropertyPathInterface

### PR DESCRIPTION
**Pull request by faizanakram99**

### CODE REVIEW

**Comment by faizanakram99** [comment]
> X and Y were meant to be just placeholders, you should type what it's really iterating over.

yep, forgot to add @template :sweat_smile: 
Fixed

**Comment by ondrejmirtes** [comment]
This will just cause another error when you typehint the interface. I suppose the iterated types are always the same, check out the implementations what's going on in them.

**Comment by faizanakram99** [comment]
> This will just cause another error when you typehint the interface. I suppose the iterated types are always the same, check out the implementations what's going on in them.

You're right, it showed implementations should be contravariant with parent errors.
From the implementations it looks like key is always integer and value is always string, fixed.

Thank you

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
