### PR TITLE
Fix hasSession specifier

### PR DESCRIPTION
**Pull request by VincentLanglet**
Closes https://github.com/phpstan/phpstan-symfony/issues/86

I didn't succeed to reproduce the test proposed here https://github.com/phpstan/phpstan-symfony/issues/86#issuecomment-871350246

But the code I added were failing prior to this change.

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Please add your efforts reproducing this case, thanks.

**Comment by VincentLanglet** [comment]
> Please add your efforts reproducing this case, thanks.

I had basically nothing.

My issue is that https://github.com/phpstan/phpstan-beberlei-assert/blob/master/tests/Type/BeberleiAssert/ImpossibleCheckTypeMethodCallRuleTest.php is a RuleTestCase but here, I'm testing a TypeSpecifier, so I don't have any rule to provide (and instead dunno how to provide the type specifier).

**Comment by ondrejmirtes** [comment]
It works exactly the same way, you just need to provide a file that shows the code that fails (but shouldn't fail).

**Comment by VincentLanglet** [comment]
> It works exactly the same way, you just need to provide a file that shows the code that fails (but shouldn't fail).

But what do I pass to
```
protected function getRule(): Rule
```
?

**Comment by ondrejmirtes** [comment]
The same thing I linked, you just copy that part.

**Comment by VincentLanglet** [comment]
> The same thing I linked, you just copy that part.

Oh my bad, I've updated the tests now. 
I check that `request_get_session.php` has no phpstan error. Without the fix I tried, and I had the "always true" error.

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
