### PR TITLE
Fix synthetic return type when class is available

### PR DESCRIPTION
**Pull request by shyim**
When a synthetic service has a class. We should use that for the type.

All tests are red on my Machine, so I didn't write a test 😓 
Issue: #154

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
@shyim Sorry, I really need the test. How are they failing on your machine?

You can also write the test and have it debugged in the CI.

**Comment by shyim** [comment]
Ahh, I was on a Tag where all tests are failed.

The class `ServiceDynamicReturnTypeExtension` doesn't have any tests yet. Is there an test helper or I really need to MethodCall and so on?

**Comment by ondrejmirtes** [comment]
Hi, it depends on what kind of error are you experiencing. You can test the right type by looking at test cases extended from `TypeInferenceTestCase`.

**Comment by Kocal** [comment]
I've testesd your pull request and I can confirm `$this->get()` inside a controller works fine.

You can apply this patch (`git apply path/to/patch`) to add tests for `$this->get()` and `$this->has()` inside a controller:
```patch
diff --git a/tests/Type/Symfony/container.xml b/tests/Type/Symfony/container.xml
index af82fd1..7437d9c 100644
--- a/tests/Type/Symfony/container.xml
+++ b/tests/Type/Symfony/container.xml
@@ -34,5 +34,6 @@

     <services>
         <service id="foo" class="Foo"></service>
+        <service id="synthetic" class="Synthetic" synthetic="true" />
     </services>
 </container>
diff --git a/tests/Type/Symfony/data/ExampleAbstractController.php b/tests/Type/Symfony/data/ExampleAbstractController.php
index 2bff754..6169b22 100644
--- a/tests/Type/Symfony/data/ExampleAbstractController.php
+++ b/tests/Type/Symfony/data/ExampleAbstractController.php
@@ -13,11 +13,13 @@ final class ExampleAbstractController extends AbstractController
 	public function services(): void
 	{
 		assertType('Foo', $this->get('foo'));
+		assertType('Synthetic', $this->get('synthetic'));
 		assertType('object', $this->get('bar'));
 		assertType('object', $this->get(doFoo()));
 		assertType('object', $this->get());

 		assertType('true', $this->has('foo'));
+		assertType('true', $this->has('synthetic'));
 		assertType('false', $this->has('bar'));
 		assertType('bool', $this->has(doFoo()));
 		assertType('bool', $this->has());
diff --git a/tests/Type/Symfony/data/ExampleAbstractControllerWithoutContainer.php b/tests/Type/Symfony/data/ExampleAbstractControllerWithoutContainer.php
index 2877382..7ca0677 100644
--- a/tests/Type/Symfony/data/ExampleAbstractControllerWithoutContainer.php
+++ b/tests/Type/Symfony/data/ExampleAbstractControllerWithoutContainer.php
@@ -12,11 +12,13 @@ final class ExampleAbstractControllerWithoutContainer extends AbstractController
 	public function services(): void
 	{
 		assertType('object', $this->get('foo'));
+		assertType('object', $this->get('synthetic'));
 		assertType('object', $this->get('bar'));
 		assertType('object', $this->get(doFoo()));
 		assertType('object', $this->get());

 		assertType('bool', $this->has('foo'));
+		assertType('bool', $this->has('synthetic'));
 		assertType('bool', $this->has('bar'));
 		assertType('bool', $this->has(doFoo()));
 		assertType('bool', $this->has());
diff --git a/tests/Type/Symfony/data/ExampleController.php b/tests/Type/Symfony/data/ExampleController.php
index db76122..fea21bd 100644
--- a/tests/Type/Symfony/data/ExampleController.php
+++ b/tests/Type/Symfony/data/ExampleController.php
@@ -13,11 +13,13 @@ final class ExampleController extends Controller
 	public function services(): void
 	{
 		assertType('Foo', $this->get('foo'));
+		assertType('Synthetic', $this->get('synthetic'));
 		assertType('object', $this->get('bar'));
 		assertType('object', $this->get(doFoo()));
 		assertType('object', $this->get());

 		assertType('true', $this->has('foo'));
+		assertType('true', $this->has('synthetic'));
 		assertType('false', $this->has('bar'));
 		assertType('bool', $this->has(doFoo()));
 		assertType('bool', $this->has());
diff --git a/tests/Type/Symfony/data/ExampleControllerWithoutContainer.php b/tests/Type/Symfony/data/ExampleControllerWithoutContainer.php
index 2adfd7d..2e9b7ba 100644
--- a/tests/Type/Symfony/data/ExampleControllerWithoutContainer.php
+++ b/tests/Type/Symfony/data/ExampleControllerWithoutContainer.php
@@ -12,11 +12,13 @@ final class ExampleControllerWithoutContainer extends Controller
 	public function services(): void
 	{
 		assertType('object', $this->get('foo'));
+		assertType('object', $this->get('synthetic'));
 		assertType('object', $this->get('bar'));
 		assertType('object', $this->get(doFoo()));
 		assertType('object', $this->get());

 		assertType('bool', $this->has('foo'));
+		assertType('bool', $this->has('synthetic'));
 		assertType('bool', $this->has('bar'));
 		assertType('bool', $this->has(doFoo()));
 		assertType('bool', $this->has());

```

**Comment by shyim** [comment]
Added :)

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
