### PR TITLE
Fix HeaderBag::all return value

### LINKED ISSUE #264: Add support for HeaderBag::all()
Since Symfony 5.4 all() has a generic return type defined which is nice, but sadly due to the $key arg it is very variable what you get back: https://github.com/symfony/symfony/blob/f5a8916bad0e45ef125d128dca6c2793bd0c55d2/src/Symfony/Component/HttpFoundation/HeaderBag.php#L66-L68

It'd be great if this extension supported all() like it does get(), switching to the correct return type based on $key being present or not.

### PR DESCRIPTION
**Pull request by Seldaek**
fixes #264

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]

**Review by ondrejmirtes — CHANGES_REQUESTED** [review]
1) I'd say there are more `*Bag` classes with the same behaviour, can you please update stubs for all of them?
2) I'd say we should be able to remove this extension altogether with the help of conditional return types: https://github.com/phpstan/phpstan-symfony/blob/1.2.x/src/Type/Symfony/InputBagDynamicReturnTypeExtension.php

**Comment by Seldaek** [comment]
Yeah, if someone else has time to take this over to do a more comprehensive fix please feel free. I don't know when I'll get to it otherwise. This isn't very high on my list.

**Comment by VincentLanglet** [comment]
For the record, the conditional type was accepted in Symfony 6.3, cf https://github.com/symfony/symfony/pull/49007

**Comment by Seldaek** [comment]
Thanks

**Pull request closed without merging**
