### PR TITLE
Change parameterbag to general type guessing

### PR DESCRIPTION
**Pull request by alexander-schranz**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Fixes https://github.com/phpstan/phpstan-symfony/issues/153

**Comment by ondrejmirtes** [comment]
FYI more tests need fixing (when ran only with lowest dependencies)

**Comment by alexander-schranz** [comment]
@ondrejmirtes I see, I did also update the other testcase.

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by alexander-schranz** [comment]
@ondrejmirtes Thx for the quick responses and release 👍

**Comment by Kocal** [comment]
Thanks!

**Pull request merged**
