### PR TITLE
Add stub for ConstraintViolationListInterface

### PR DESCRIPTION
**Pull request by ossinkine**

### CODE REVIEW

**Comment by ossinkine** [comment]
Could someone test this? I've added this to my project and got the error `PHPDoc tag @extends has invalid type Symfony\Component\Validator\ConstraintViolationInterface` and I have no idea why.

**Comment by ossinkine** [comment]
Checks aldo failed, @ondrejmirtes could you help?

**Comment by ondrejmirtes** [comment]
The documentation states why you got this error: https://phpstan.org/user-guide/stub-files

See the section "Why is PHPStan complaining about “Class not found” in a stub file?".

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
