### PR TITLE
Add generics for PasswordUpgraderInterface

### PR DESCRIPTION
**Pull request by VincentLanglet**
This is https://github.com/symfony/symfony/pull/48750 but for older Symfony version.
I'll wait for the Symfony merge this.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
https://github.com/symfony/symfony/pull/48750 was merged so this is ready to be merged @ondrejmirtes

**Comment by ondrejmirtes** [comment]
I can only merge this if the new generic class is added to `skipCheckGenericClasses` in `extension.neon`.

**Comment by VincentLanglet** [comment]
> skipCheckGenericClasses

Done !
What's the idea behind ? Is it for BC purpose ?

**Comment by ondrejmirtes** [comment]
Yes, I'm gonna empty it in the next major version.

**Comment by ondrejmirtes** [comment]
Thank you!

**Comment by VincentLanglet** [comment]
> Yes, I'm gonna empty it in the next major version.

I assume that if you use bleedingEdge, skipCheckGenericClasses has no effect ?

**Comment by ondrejmirtes** [comment]
There's https://github.com/phpstan/phpstan-src/blob/3408a97088d6af676114814fa83455b11ac4da76/conf/bleedingEdge.neon#L4 but I think that only applies to https://github.com/phpstan/phpstan-src/blob/3408a97088d6af676114814fa83455b11ac4da76/conf/config.neon#L23-L33 because phpstan-symfony config is applied later. Anyway, you can verify this yourself :)

**Pull request merged**
