### PR TITLE
Separate rules from extension as in other phpstan extensions

### PR DESCRIPTION
**Pull request by mcfedr**
Doing this because issue of false positives in test cases, https://github.com/phpstan/phpstan-symfony/issues/27, but anyway, its the style in all the other phpstan plugins, so would be good to do the same here

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
I agree, but README also needs updating and this can be released as 0.12 because it's a BC break.

**Comment by mcfedr** [comment]
Added README changes

**Comment by ondrejmirtes** [comment]
This needs rebasing because of new rules and conflict in extension.neon

**Comment by lookyman** [comment]
Thanks!

**Pull request merged**
