### PR TITLE
Travis > Test on PHP 7.4

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, updating CS is not that easy. You'd have to do the same approach I did here: https://github.com/phpstan/phpstan-src/commits/master/build-cs

**Comment by ruudk** [comment]
Thanks :) Will have a look.

**Comment by ruudk** [comment]
@ondrejmirtes It's green ✅ 

I'm preparing PR's for all the other repo's with the same trick. Thanks.

**Comment by ondrejmirtes** [comment]
Thank you! Looking forward to that :)

**Comment by ruudk** [comment]
I created the PR's for all the repositories and they are all ✅ 🎉 
https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3Aruudk+archived%3Afalse+user%3Aphpstan+

**Pull request merged**
